django-project/jartmanagement/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("mediaserver.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

django-project/mediaserver/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("robots.txt", views.robots, name="robots.txt"),
    path("manage/gallery/<int:gallery_id>", views.edit_gallery, name="edit_gallery"),
    path("gallery/<int:gallery_id>", views.gallery, name="gallery"),
    path("galleries", views.galleries, name="galleries"),
    path("galleries/latest", views.latest_gallery, name="latest_gallery"),
    path("galleries/latest/<str:category>", views.latest_gallery_by_category, name="latest_gallery_by_category"),
    
    path("create/media", views.create_media, name="create_media"),
    path("create/media/tokenauth", views.create_media_with_token, name="create_media_with_token"),
    path("create/mediaEmbed", views.create_embedded_media, name="create_embedded_media"),
    path("create/gallery", views.create_gallery, name="create_gallery"),
    path("delete/gallery/<int:gallery_id>", views.delete_gallery, name="delete_gallery"),
    path("delete/media/<uuid:media_uuid>", views.delete_media, name="delete_media"),
    path("objects/orphaned", views.orphaned_media, name="orphaned_media"),
    path("objects/detach/<uuid:media_uuid>", views.detach_media, name="detach_media"),
    path("objects/<uuid:media_uuid>/gallery", views.get_media_gallery, name="get_media_gallery"),
    path("objects/gallery/<int:gallery_id>/media", views.get_gallery_media, name="get_gallery_media"),
    path("objects/gallery/<int:gallery_id>/metadata", views.get_gallery_metadata, name="get_gallery_metadata"),
    path("categories/json", views.get_categories, name="get_categories"),
    path("modify/media", views.modify_media, name="modify_media"),
    path("modify/gallery/<int:gallery_id>/media", views.update_gallery_media, name="update_gallery_media"),
    path("modify/gallery/<int:gallery_id>/title", views.update_gallery_title, name="update_gallery_title"),
    path("modify/gallery/<int:gallery_id>/visibility", views.update_gallery_visibility, name="update_gallery_visibility"),
    path("modify/gallery/<int:gallery_id>/date", views.update_gallery_date, name="update_gallery_date"),
    path("modify/gallery/<int:gallery_id>/category", views.update_gallery_category, name="update_gallery_category"),
    path("modify/gallery/<int:gallery_id>/associate_media", views.associate_media, name="associate_media"),
    path("modify/gallery/<int:gallery_id>/associate_single_media", views.add_single_media, name="add_single_media"),

    re_path(r'^creator/(?P<tag>.+?)$', views.CreatorTagListView.as_view(template_name="galleries/tag_list.html"), name="media_by_creator_tag"),
    re_path(r'^tags/(?P<namespace>\w+)/(?P<tag>.+?)$', views.TagListView.as_view(template_name="galleries/tag_list.html"), name="media_by_tag"),

    path("gallery/media/<uuid:media_uuid>", views.MediaView.as_view(template_name="galleries/media_item.html"), name="media_detail"),

    path("tags/", views.all_tags, name="all_tags"),
    path("tags/discordLink", views.set_discord_user_tag, name="set_discord_user_tag"),
    path("objects/discordUnlink", views.remove_discord_user, name="remove_discord_user"),

    path("tags/autocomplete/", views.tags_by_startswith, name="tags_by_startswith"),

    #override allauth non-login urls
    re_path(r'^accounts\/(password|confirm-email|email).*', views.redirect_home, name="index_redirect"),
    path("accounts/signup/", views.redirect_login, name="login_redirect"),
    path("accounts/login/", views.redirect_login, name="login_redirect"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-project/mediaserver/models.py
from django.db import models
from django.conf import settings
from django.db.models import QuerySet
import uuid

class Tag(models.Model):
    tagname = models.CharField(max_length=256)
    namespace = models.CharField(max_length=256, blank=True)
    displayName = models.CharField(max_length=265, blank=True)

    description = models.TextField(blank=True)

    tag_count = models.IntegerField(default=0)

    # Forward reference to Media model fields
    creator_tags: "models.ManyToManyField[Tag, Media]"
    tags: "models.ManyToManyField[Tag, Media]"
    # Forward reference to discord model field
    assoc_discord: "models.Manager[DiscordCreator]"


    def count_uses(self):
        self.tag_count = self.tags.count() + self.creator_tags.count()
        discord_creator = self.assoc_discord.first()
        if discord_creator: 
            self.tag_count += discord_creator.count_uses()
        self.save()
        if(self.tag_count <= 0):
            self.delete()


    @staticmethod
    def clear_orphans():
        counter = 0
        for tag in Tag.objects.filter(tags=None).filter(creator_tags=None).filter(assoc_discord=None):
            counter += 1
            tag.delete()
        print(f"Deleted {counter} orphaned tags")
    
    @staticmethod
    def count_tags():
        for tag in Tag.objects.all():
            precount = tag.tag_count
            tag.count_uses()
            postcount = tag.tag_count
            if postcount != precount:
                print(f'{tag.namespace}:{tag.tagname} | {precount} -> {postcount}')

    def __str__(self):
        return f'{self.namespace}:{self.tagname}'
    
    class Meta:
        ordering = ['namespace', 'tagname']

class DiscordCreator(models.Model):
    username = models.CharField(max_length=256)
    tag = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True, related_name='assoc_discord')

    # Forward reference to Media model field
    assoc_media: "models.Manager[Media]"

    def count_uses(self):
        uses = self.assoc_media.count()
        return uses

class Media(models.Model):
    file = models.FileField(default='default.jpg')
    creator_tags = models.ManyToManyField(Tag, blank=True, related_name='creator_tags')
    discord_creator = models.ForeignKey(DiscordCreator, on_delete=models.SET_NULL, null=True, related_name='assoc_media')
    title = models.CharField(max_length=256, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    uploaderDescription = models.TextField(blank=True)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    type = models.CharField(max_length=64)
    height = models.IntegerField(null=True)
    width = models.IntegerField(null=True)
    loop = models.BooleanField()
    tags = models.ManyToManyField(Tag, blank=True, related_name='tags')
    uploaded_date = models.DateTimeField("date uploaded", auto_now_add=True)

    @property
    def creators(self) -> list[Tag]:
        if self.discord_creator and self.discord_creator.tag:
            tags = list(self.creator_tags.all())
            tags.append(self.discord_creator.tag)
            return tags
        else:
            return list(self.creator_tags.all())

    def __str__(self):
        return f'{self.file.name} - {self.type} file by {self.creator_tags.first()}'
    
class EmbeddedMedia(Media):
    url = models.URLField()
    def __str__(self):
        return f'{self.url} - {self.type} file by {self.creator_tags.first()}'

class Gallery(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=256)
    created_date = models.DateTimeField("date created", auto_now_add=True)
    media_items = models.ManyToManyField(Media, through="GalleryOrder", related_name="media_gallery")
    category = models.CharField(max_length=64)
    visible = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
class GalleryOrder(models.Model):
    media =  models.ForeignKey(Media, on_delete=models.CASCADE)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    order = models.IntegerField()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['media', 'gallery'], name="Every image has one gallery")
        ]

django-project/mediaserver/forms.py
from django import forms
from .models import Media, EmbeddedMedia

class NewImageForm(forms.ModelForm):
    class Meta:
        model = Media
        fields = ['file', 'title', 'description', 'uploaderDescription', 'type', 'height', 'width', 'loop', 'uploader']

class NewMediaRemoteForm(forms.ModelForm):
    class Meta:
        model = Media
        fields = ['file', 'creator_tags', 'description', 'type', 'height', 'width', 'uploader']

class NewEmbedForm(forms.ModelForm):
    class Meta:
        model = EmbeddedMedia
        fields = ['url', 'title', 'description', 'uploaderDescription', 'type', 'height', 'width', 'loop', 'uploader']

class ImageMetadataForm(forms.Form):
    uuid = forms.UUIDField(required=True)
    title = forms.CharField(max_length=256, required=False)
    creator_tags = forms.CharField(required=False)
    tags = forms.CharField(required=False)
    description = forms.CharField(required=False)
    uploaderDescription = forms.CharField(required=False)
    loop = forms.BooleanField(required=False)

django-project/mediaserver/templates/galleries/gallery.html
{% extends 'base.html' %}
{% load static %}
{% load media_utility %}
{% block title %}{{ site_brand_name }} - {{gallery.title}}{% endblock title %}
{% block embed-title %}{{ site_brand_name }} | {{gallery.title}}{% endblock embed-title %}

{% block page-style %}
<link rel="stylesheet" href="{% static 'gallery-style.css' %}">
<link rel="stylesheet" href="{% static 'photoswipe/photoswipe.css' %}">
<link rel="stylesheet" href="{% static 'photoswipe/photoswipe-dynamic-caption-plugin.css' %}">
<style id="pixelatedStyle" disabled="false">
    .pswp__img {
        /*Browsers don't seem to respect disabled="true" on page load
        so the style is pixelated when pixelatedStyle is FALSE*/
        image-rendering: auto; 
    }
</style>
{% endblock page-style %}

{% block body-content %}
<main>
    <div id="galleryContainer">
        {% block gallery-title %}
        <div id="titleContainer">
            <h2>{{ gallery.title }}{% if perms.mediaserver.change_gallery %}<span>&nbsp[<a href="{% url 'edit_gallery' gallery.id %}">Edit</a>]</span>{% endif %}</h2>
            <p>{{ gallery.created_date|date:"jS F, Y" }}</p>
        </div>
        {% if istoday %}
        <div id="reminder" class="banner">
            <h2>Artists!</h2>
            <p>{{ site_brand_plea }}</p>
        </div>
        {% endif %}
        {% endblock gallery-title %}
        {% for media in page_obj %}
        <div class="album-image">
            {% if 'embed' in media.type %}
            <a href="{{ media.embeddedmedia.url }}?rel=0"
                class="album-media-item"
                data-pswp-width="{{media.width}}"
                data-pswp-height="{{media.height}}"
                data-pswp-embed="true"
                target="_blank">
                <iframe 
                    src="{{ media.embeddedmedia.url }}?rel=0" 
                    width="100%" 
                    frameborder="0" 
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                    referrerpolicy="strict-origin-when-cross-origin" 
                    allowfullscreen>
                </iframe>
            </a>
            {% elif 'image/' in media.type %}
            <a href="{{ media.file.url }}"
                class="album-media-item"
                data-pswp-width="{{media.width}}"
                data-pswp-height="{{media.height}}"
                target="_blank">
                <img src="{{ media.file.url }}" alt="{{media.title}}" {% image_size media.width media.height %} loading="lazy">
            </a>
            {% elif 'video/' in media.type %}
            <a href="{{ media.file.url }}"
                class="album-media-item"
                data-pswp-width="{{media.width}}"
                data-pswp-height="{{media.height}}"
                data-pswp-video-src="{{media.file.url}}"
                data-pswp-video-loop={{media.loop}}
                target="_blank">
                <video src="{{ media.file.url }}" controls {% if media.loop %}loop="true"{% endif %}>
            </a>
            {% else %}
            <p class="unsupportedFiletypePlaceholder">Unsupported Filetype</p>
            {% endif %}
            <span class="mediaDescription">
                {% autoescape on %}
                {% if media.title and media.title.strip %}<strong>{{media.title}}</strong>{% endif %}
                {% if media.creators%}
                <div class="tagContainer">
                {% for tag in media.creators %}
                <a data-tag-namespace="creator" data-tag-tagname="{{tag.tagname}}" class="tag" href="/creator/{{tag.tagname}}" title="Creator: {{tag.tagname}}">
                    <div class="tagLabel">
                    {{tag.tagname}}
                    </div>
                    <div class="tagCount">{{tag.tag_count}}</div>
                </a>
                {% endfor %}
                </div>
                {% endif %}
                {% if media.description and media.description.strip %}
                <p class="creatorDescription">
                    "{{media.description|linebreaksbr|urlize}}"
                </p>
                {% endif %}
                {% if media.uploaderDescription and media.uploaderDescription.strip %}
                <p class="uploaderDescription">
                    {{media.uploaderDescription|linebreaksbr|urlize}}
                </p>
                {% endif %}
                {% if media.tags%}
                <div class="tagContainer">
                {% for tag in media.tags.all %}
                <a data-tag-namespace="{{tag.namespace}}" data-tag-tagname="{{tag.tagname}}" class="tag" href="/tags/{{tag.namespace|default:"all"}}/{{tag.tagname}}" title="{{tag.namespace}}:{{tag.tagname}}">
                    <div class="tagLabel">
                    {{tag.tagname}}
                    </div>
                    <div class="tagCount">{{tag.tag_count}}</div>
                </a>
                {% endfor %}
                </div>
                {% endif %}
                
                {% block description_end %}
                {% endblock description_end %}
                {% endautoescape %}
            </span>
            <a class="permalink" href="/gallery/media/{{media.uuid}}" class="permalink" title="Direct link to this media">🔗</a>
            {% block media-element-end %}
            {% endblock media-element-end %}
        </div>
        {% endfor %}
    </div>
</main>
{% block pagination %}{% endblock pagination %}
{% endblock body-content %}

{% block after-body %}
<script type="module">
    import PhotoSwipeLightbox from '{% static "photoswipe/photoswipe-lightbox.esm.js" %}';
    import PhotoSwipeDynamicCaption from '{% static "photoswipe/photoswipe-dynamic-caption-plugin.esm.js" %}'
    import PhotoSwipe from '{% static "photoswipe/photoswipe.esm.js" %}';

    const pixelatedStyle = document.getElementById('pixelatedStyle');
    const galleryElement = document.getElementById('galleryContainer');
    const albumImages = galleryElement.querySelectorAll('.album-image');

    const lightbox = new PhotoSwipeLightbox({
        gallery: '#galleryContainer',
        children: '.album-image > a.album-media-item',
        pswpModule: PhotoSwipe,
        bgOpacity: 1,
        clickToCloseNonZoomable: false,
        secondaryZoomLevel: 1,
        
        paddingFn: (viewportSize) => {
            return {
            top: 30, bottom: 30, left: 70, right: 70
            }
        },
    });

    const captionPlugin = new PhotoSwipeDynamicCaption(lightbox, {
        type: 'auto',
        captionContent: (slide) => {
            if(slide.data.element?.parentNode.querySelector('span')) {
                return slide.data.element.parentNode.querySelector('span').innerHTML;
            }
            else {
                return '';
            }
        }
    });

    lightbox.on('uiRegister', function() {
        lightbox.pswp.ui.registerElement({
            name: 'pixelButton',
            title: 'Toggle pixelated rendering',
            ariaLabel: 'Toggle pixelated rendering',
            order: 9,
            isButton: true,
            html: '🏁',
            onClick: (event, el) => {
                pixelatedStyle.disabled = !pixelatedStyle.disabled;
            }
        });
        lightbox.pswp.ui.registerElement({
            name: 'refreshButton',
            title: 'Reload video',
            ariaLabel: 'Reload video',
            order: 10,
            isButton: true,
            html: '🔄',
            onClick: (event, el) => {
                if (lightbox.pswp.currSlide.content.element.tagName.toLowerCase() == 'video') {
                    lightbox.pswp.currSlide.content.element.load();
                }
            }
        })
    });
        
    lightbox.on('closingAnimationEnd', () => {
        let open_index = lightbox.pswp.currSlide.index;
        console.log(open_index);
        albumImages[open_index].scrollIntoView({behavior: "smooth", block: "end"});
    });

    lightbox.init();

    lightbox.addFilter('itemData', (itemData, index) => {
        const videoSrc = itemData.element.dataset.pswpVideoSrc;
        const loopVideo = itemData.element.dataset.pswpVideoLoop;
        const embed = itemData.element.dataset.pswpEmbed;
        if (videoSrc) {
            itemData.videoSrc = videoSrc;
            itemData.loopVideo = loopVideo;
        }
        if (embed) {
            itemData.embed = embed;
        }
        return itemData;
    });

    lightbox.on('contentLoad', (e) => {
        const { content, isLazy } = e;
        if(content.data.videoSrc) {
            e.preventDefault();

            content.element = document.createElement('video');
            content.element.src = content.data.videoSrc;
            content.element.autoplay = false;
            if (content.data.loopVideo) {
                content.element.loop = (content.data.loopVideo == "True");
            }
            content.element.controls = true;
            content.element.preload = 'auto';
        }
        if (content.data.embed) {
            e.preventDefault();
            content.element = document.createElement('iframe');
            content.element.src = content.data.src;
            content.element.width = content.data.width;
            content.element.height = content.data.height;
            content.element.allow = 'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';
            content.element.referrerPolicy = 'strict-origin-when-cross-origin'
            content.element.allowFullscreen = true;
        }
    });

    lightbox.addFilter('useContentPlaceholder', (useContentPlaceholder, content) => {
        if(content.data.videoSrc) {
            return false;
        }
        return useContentPlaceholder;
    });
    lightbox.addFilter('isContentLoading', (isContentLoading, content) => {
        if(content.data.videoSrc) {
            return false;
        }
        return isContentLoading;
    });
</script>
{% endblock after-body %}

django-project/mediaserver/templates/galleries/holiday.html
{% extends "galleries/gallery.html" %}
{% load static %}

{% block page-style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'holiday.css' %}">
{% endblock page-style %}

{% block media-element-end %}
<div class="holiday-gift-overlay">
    <div class="door-1"></div>
    <div class="door-2"></div>
    <div class="ribbon-horizontal"></div>
    <div class="ribbon-vertical"></div>
    <div class="bow"></div>
</div>
{% endblock media-element-end %}

{% block after-body %}
<script>
    let overlays = document.querySelectorAll('.holiday-gift-overlay');

    for (const overlay of overlays) {
        overlay.addEventListener('click', () => {
            overlay.classList.add('opened');
        });
    }
</script>
{{ block.super }}
{% endblock after-body %}

django-project/mediaserver/templates/galleries/index.html
{% extends 'base.html' %}
{% load static %}
{% load media_utility %}

{% block title %}{{ site_brand_name}} - {{ site_brand_desc }}{% endblock title %}
{% block page-description %}Archiving Joe Fanart since July 2023{% endblock %}
{% block page-style %}<link rel="stylesheet" href="{% static 'index.css' %}">{% endblock page-style %}

{% block body-content %}
{% regroup gallery_list by category as category_list %}
<main>
    <h1>Galleries</h1>
    <ul id="galleryList">
        {% for category in category_list %}
        <h2>{{ category.grouper|underscore_to_space|title }}</h2>
        {% for gallery in category.list %}
            {% if gallery.visible or perms.mediaserver.change_gallery %}
            <li {% if not gallery.visible %}class="hidden"{% endif %}>
                <span>
                    <a href="{% url 'gallery' gallery.id %}">{{ gallery.title }}</a>
                    <span class="gallery-date">{{ gallery.created_date|date:"jS F, Y" }}</span>
                {% if perms.mediaserver.change_gallery %}
                    <a href="{% url 'edit_gallery' gallery.id %}">edit</a> {% if perms.mediaserver.delete_gallery %} | 
                    <form action="{% url 'delete_gallery' gallery_id=gallery.id%}", method="POST">
                        <button class="delete" type="submit" onclick="return confirm('Are you SURE you want to delete this gallery?');">delete</button>
                        {% csrf_token %}
                    </form>
                    {% endif %}
                {% endif %}
                </span>
            </li>
            {% endif %}
        {% endfor %}
        {% endfor %}
    </ul>
    {% if perms.mediaserver.add_gallery %}
    <form action="{% url 'create_gallery' %}" method="post">
        {% csrf_token %}
        <button type="submit">+ New Gallery</a>
    </form>
    {% endif %}
</main>
<div itemscope itemtype="https://schema.org/WebSite">
    <link itemprop="url" href="{{ site_brand_url }}" />
    <meta itemprop="name" content="{{ site_brand_name }}" />
</div>
{% endblock body-content %}

django-project/mediaserver/templates/galleries/manage_gallery.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Gallery{% endblock title %}

{% block page-style %}
<link rel="stylesheet" href="{% static 'manage_gallery_index.css' %}">
{% endblock page-style %}

{% block body-content %}
<div id="app"></div>
{% endblock body-content %}

{% block after-body %}
<script type="module" src="{% static 'manage_gallery_index.js' %}"></script>
{% endblock after-body %}

django-project/mediaserver/templates/galleries/media_item.html
{% extends "galleries/gallery.html" %}

{% block title %}{{ site_brand_name }} - Fanart by {{page_obj.0.creators.0.tagname}}{% endblock title %}
{% block embed-title %}{{ site_brand_name }} | Fanart by {{page_obj.0.creators.0.tagname}}{% endblock embed-title %}
{% block page-description %}{{tag.tag_count}} fanart created by {{page_obj.0.creators.0.tagname}}{% endblock %}

{% block gallery-title %}
{% endblock gallery-title %}

{% block description_end %}
{% with gallery=media.media_gallery.first %}
{% if gallery and gallery.visible or perms.mediaserver.change_gallery %}
<p>Originally seen at <a href="/gallery/{{gallery.id}}">{{gallery.title}}</a></p>
{% else %}
<p style="color: gray; font-style: italic;">This post has not appeared in a gallery yet.</p>
{% endif %}
{% endwith %}
{% endblock description_end %}

django-project/mediaserver/templates/galleries/orphaned_media.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}Edit Gallery{% endblock title %}

{% block page-style %}
<style>
    main {
        display: flex;
        flex-direction: row;
        max-width: 1600px;
        min-width: 800px;
        margin: 0 auto;
        gap: 1rem;

        > div {
            width: 50%;
        }
    }
    .media {
        display: flex;
        flex-direction: row;
        align-items: center;
        margin: 1rem;
        border: 2px solid white;
        gap: 1rem;

        .thumb {
            height: 100px;
            width: 100px;
        }
        p {
            flex-grow: 1;
            overflow: scroll;
        }
        button {
            height: 100px;
            width: 100px;
            fit-content: center;
            justify-self: end;
        }
    }

    .media:has(img:hover) > .previewOverlay {
        display: block;
    }
    
    .previewOverlay {
        display: none;
        position: fixed;
        top: 1rem;
        left: 1rem;
        bottom: 1rem;
        right: 1rem;
        pointer-events: none;
        z-index: 1;
    
        img {
            max-width: 100%;
            max-height: 100%;
        }
    }
    
</style>
{% endblock page-style %}

{% block body-content %}
<main>
    <div>
        <h1>Orphaned files</h1>
        <div>
            {% for media in orphaned_media %}
                <div class="media">
                    {% if media.type == 'image/gif' %}
                    <img class="thumb" src="{{ media.file }}" alt="{{ media.file.name }}">
                    {% elif 'image/' in media.type %}
                    <img class="thumb" src="{{ media.file|thumbnail_url:'100' }}" alt="{{ media.file.name }}">
                    {% elif 'video/' in media.type %}
                    <video class="thumb" src="/media/{{ media.file }}" controls></video>
                    {% endif %}
                    <p>{{ media.file.name }}</p>
                
                    <form action="{% url 'delete_media' media_uuid=media.uuid%}", method="POST">
                        <button class="delete" type="submit" onclick="return confirm('Are you SURE you want to delete this file?');">delete</button>
                        {% csrf_token %}
                    </form>
                    <form action="">
                        <button class="add" type="button" onclick="add_media_to_gallery(this, event);">➡️</button>
                        <input type="hidden" name="uuid" value="{{ media.uuid }}">
                        {% csrf_token %}
                    </form>

                    <div class="previewOverlay">
                        <img src="/media/{{ media.file }}" alt="" loading="lazy"/>
                    </div>        
                </div>
            {% endfor %}
        </div>
    </div>
    <div>
        <h1>Galleries</h1>
        <fieldset>
            <legend>Target gallery</legend>
            
            <select name="gallery" size="{{galleries|length}}" id="">
            {% for gallery in galleries %}
                <option value="{{ gallery.id }}">{{ gallery.title }}</option>
            {% endfor %}
            </select>
        </fieldset>
    </div>
</main>

{% endblock body-content %}

{% block after-body %}
<script>
    const csrf_token = "{{ csrf_token }}";
    const gallery_field = document.querySelector('select[name="gallery"]');
    gallery_field.selectedIndex = 0;

    function add_media_to_gallery(element, event) {
        const media_id = event.target.form['uuid'].value;
        const gallery_id = gallery_field.value;
        let request = new Request(`/modify/gallery/${gallery_id}/associate_single_media`, {
            method: "POST",
            body: media_id,
            headers: { 'X-CSRFToken': csrf_token }
        });
        fetch(request).then((response) => {
            console.log(response);
            if (response.status == 200) {
                window.location.reload();
            }
        });    
    }
</script>
{% endblock after-body %}

django-project/mediaserver/templates/galleries/tag_list.html
{% extends "galleries/gallery.html" %}

{% block title %}{{ site_brand_name }} - Tag: {{tag.tagname}}{% endblock title %}
{% block embed-title %}{{ site_brand_name }} | Tag: {{tag.namespace}}:{{tag.tagname}}{% endblock embed-title %}
{% block page-description %}{{tag.tag_count}} fanart tagged with {{tag.namespace}}:{{tag.tagname}}{% endblock %}
{% block extra-metadata %}
    {% if tag.namespace == "creator" %}
    <link rel="canonical" href="https://{{request.get_host}}/creator/{{tag.tagname}}">
    {% else %}
    <link rel="canonical" href="https://{{request.get_host}}/tags/{{tag.namespace}}/{{tag.tagname}}">
    {% endif %}
{% endblock extra-metadata %}

{% block gallery-title %}
<h2>Tag: {{tag.namespace}}:{{tag.tagname}} ({{tag.tag_count}} image{{ tag.tag_count|pluralize }})</h2>
{% if tag.description %}
<div id="tag-description" class="banner">
    <h2>About</h2>
    {{ tag.description|linebreaksbr|urlize }}
</div>
{% endif %}
{% endblock gallery-title %}

{% block description_end %}
{% with gallery=media.media_gallery.first %}
{% if gallery and gallery.visible or perms.mediaserver.change_gallery %}
<p>Originally seen at <a href="/gallery/{{gallery.id}}">{{gallery.title}}</a></p>
{% else %}
<p style="color: gray; font-style: italic;">This post has not appeared in a gallery yet.</p>
{% endif %}
{% endwith %}
{% endblock description_end %}

{% block pagination %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}" rel="prev">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" rel="next">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock pagination %}